### ISSUE TITLE
"All the wolves have died" endgame message when SK loses and no WW is in-game

### ISSUE THREAD

**Issue by RaptDept** [parabola949/Werewolf#37] opened 2016-07-02 07:29 UTC
Endgame message erroneously states that Werewolves have won when the SK wins.

It should be noted that I found this while playing Chaos mode where there were zero werewolves and one SK.

EDIT:
Made a mistake, the issue here is "The villagers have won! All the wolves have died..." appears when SK dies and there's no WW.

**Comment by parabola949** [comment] 2016-07-07 16:58
Could you give me the group id (use /chatid) it happened in, and what time (UTC) approximately?

**Comment by RaptDept** [comment] 2016-07-19 07:02
Sorry, I made a mistake. The issue was that "The villagers have won! All the wolves have died..." appears when the SK dies and there's no werewolf. Will edit this post to reflect that.

Here's the last time it happened:
Chat ID: -148549990
July 19 4:04 AM UTC

**Comment by kamikazechaser** [comment] 2016-09-11 16:41
This bug is caused by the fact that a team VG win assumes only wolves were defeated, yet in some cases a SK may be the only negative player in the game (see below). 
A decent fix would be to create two cases in Werewolf/Werewolf for Telegram/Werewolf Node/Werewolf.cs : **VillagersWinWolf** and **VillagersWInSerialKiller** and then to add their respective strings to the language xml files.
![image 001 19 19](https://cloud.githubusercontent.com/assets/18488025/18418865/07909746-7857-11e6-9d10-906ae71a26e0.jpg)

**Comment by renyhp** [comment] 2016-09-11 16:51
@kamikazechaser Another fix, much simpler, would be simply rewording the string. Renaming a string and principally adding another string would mean telling the translators to do that on their langfiles (although they should reword the string in any case...)

**Comment by kamikazechaser** [comment] 2016-09-11 18:11
@renyhp True!, this would be very easy, however the ambiguity should be removed hence the final sentence should be something like "The villagers have won!", only.

**Comment by renyhp** [comment] 2016-09-11 21:17
Fixed in commit 1c83689b10e64177fda4e23a6c3eb0163dfa3a7c

**Closed** 2016-09-16 14:25 UTC
Labels: bug
