### ISSUE TITLE
Overtime

### ISSUE THREAD

**Issue by 67-P** [parabola949/Werewolf#126] opened 2016-10-01 15:57 UTC
As we all know the wolf gets to stay at home for 1 night if he eats the Drunk.
But it's a bit of a waste of time to wait a full day if there are only 2 players left alive, because they would tie their votes and the wolf would still win.
I've been informed that it has been made like this probably to still give a chance to Village Team to win, if the wolf forgot to lynch, but in my honest opinion  trying to disadvantage so much wolves isn't very fair.
So if the timeout could be removed it would be much appreciated.
Thank you for reading.

**Comment by renyhp** [comment] 2016-10-01 16:45
We are aware of this, and this issue is a duplicate of #104. I'm closing this one, please post further comments there.
Anyway, I'm going to change this, and make those games end immediately.

**Closed by renyhp** 2016-10-01 16:45 UTC
