### ISSUE TITLE
[Bug] lone villager & wolf alive on the last day

### ISSUE THREAD

**Issue by joshkurien** [parabola949/Werewolf#119] opened 2016-09-20 17:24 UTC
### Game
20 Sep 9:54 IST (GMT + 5:30)

### Description
Drunk is killed on second last night by wolf. One Villager and One Wolf left; Game does not end and continues to last day where both lynch each other

![ww1](https://cloud.githubusercontent.com/assets/7813196/18680844/0835ffdc-7f83-11e6-8124-03df44d46d56.jpg)

### Final result
After lynch (no conclusion) wolf wins by default as there is only one villager left
 
![ww3](https://cloud.githubusercontent.com/assets/7813196/18680903/3113cb3c-7f83-11e6-8427-34726fe2902a.jpg)

**Comment by renyhp** [comment] 2016-09-20 20:35
The code is made so that, if werewolves have just eaten the drunk, even if they are 50% of village population, they don't automatically win. We already know that this is a problem, and there are games should automatically end in such cases. We are not sure if there are some similar cases in which the village can still win. There will be an update as soon as we can figure something out.
Anyway, this is an already known bug, I'm closing this issue because it's a duplicate of #104. Please post any further comment there.

**Closed by renyhp** 2016-09-20 20:35 UTC
